// function getNextPalindromes(dateEnString, x) {
//     let [newDay, newMonth, newYear] = decomposeDate(dateEnString); 
//     ; 
//     i=0; 
//     let Tabpalindromes =[]; 
//     while (i < x) {
        
      // do{
    //     newDay++
    //     if (newDay >= maxDaysInMonth) {
    //         newDay = 1;
    //         newMonth++;
    //     }
    //     if (newMonth >= 12) {
    //         newYear++;
    //         newMonth = 1;
    //     }
    //     i++
    //     console.log("GetNextMonth: " + newDay, newMonth, newYear)
    // } while (newYear === 2023)
    // do {
    //     newDay++;
    //     if (newDay >= maxDaysInMonth(newMonth, newYear)) {
    //         newDay = 1;
    //         newMonth++;
    //     }
    //     if (newMonth >= 12) {
    //         newYear++;
    //         newMonth = 1;
    //     }
    //     console.log("GetNextMonth: " + newDay, newMonth, newYear);
    // } while (newYear <= 2023);

    // let numberPalindrome
    // let arrayPalindrome = []
    // do {
    //     arrayPalindrome += arrayPalindrome.push(isPalindrome(dateEnString))
    // } while (numberPalindrome = x)
//}

// function getNextPalindromes(date, x) {
//     console.log(typeof date)
//     let [newDay, newMonth, newYear] = decomposeDate(date)
//     console.log("test" + decomposeDate(date))
//     console.log("GetNextMonth: " + newMonth)
//     let arrayPalindrome = []
//     let newDayStringg = ""
//     let newMonthStringg = ""
//     let newYearStringg = ""
//     let dateString = ""
//   console.log(decomposeDate(date))
//     for (let i = 0; i < x; i++) {
//         if (newDay > maxDaysInMonth(newDay, newMonth, newYear)) {
//             newMonth++
//             newDay = 1
//         }
//         if (newMonth > 12) {
//             newYear++
//             newMonth = 1
//         }
//         newDayStringg = String(newDay)
//         newMonthStringg = String(newMonth)
//         newYearStringg = String(newYear)
//         dateString = newDayStringg + "/" + newMonthStringg + "/" + newYearStringg
//         console.log(dateString)
//         if (isPalindrome() === true) {
//             arrayPalindrome.push(dateString)
//         }
//     }
//     console.log(arrayPalindrome)
//     return arrayPalindrome
// }
